server:
  port: 8083

spring:
  datasource:
    username: psql
    password: password
    url: jdbc:postgresql://localhost:5432/psql
    driver-class-name: org.postgresql.Driver


keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: bael-admin
      password: pass
    realmImportFile: baeldung-realm.json
